__all__ = [
    "KEY_RESERVED",
    "KEY_ESC",
    "KEY_1",
    "KEY_2",
    "KEY_3",
    "KEY_4",
    "KEY_5",
    "KEY_6",
    "KEY_7",
    "KEY_8",
    "KEY_9",
    "KEY_0",
    "KEY_MINUS",
    "KEY_EQUAL",
    "KEY_BACKSPACE",
    "KEY_TAB",
    "KEY_Q",
    "KEY_W",
    "KEY_E",
    "KEY_R",
    "KEY_T",
    "KEY_Y",
    "KEY_U",
    "KEY_I",
    "KEY_O",
    "KEY_P",
    "KEY_LEFTBRACE",
    "KEY_RIGHTBRACE",
    "KEY_ENTER",
    "KEY_LEFTCTRL",
    "KEY_A",
    "KEY_S",
    "KEY_D",
    "KEY_F",
    "KEY_G",
    "KEY_H",
    "KEY_J",
    "KEY_K",
    "KEY_L",
    "KEY_SEMICOLON",
    "KEY_APOSTROPHE",
    "KEY_GRAVE",
    "KEY_LEFTSHIFT",
    "KEY_BACKSLASH",
    "KEY_Z",
    "KEY_X",
    "KEY_C",
    "KEY_V",
    "KEY_B",
    "KEY_N",
    "KEY_M",
    "KEY_COMMA",
    "KEY_DOT",
    "KEY_SLASH",
    "KEY_RIGHTSHIFT",
    "KEY_KPASTERISK",
    "KEY_LEFTALT",
    "KEY_SPACE",
    "KEY_CAPSLOCK",
    "KEY_F1",
    "KEY_F2",
    "KEY_F3",
    "KEY_F4",
    "KEY_F5",
    "KEY_F6",
    "KEY_F7",
    "KEY_F8",
    "KEY_F9",
    "KEY_F10",
    "KEY_NUMLOCK",
    "KEY_SCROLLLOCK",
    "KEY_KP7",
    "KEY_KP8",
    "KEY_KP9",
    "KEY_KPMINUS",
    "KEY_KP4",
    "KEY_KP5",
    "KEY_KP6",
    "KEY_KPPLUS",
    "KEY_KP1",
    "KEY_KP2",
    "KEY_KP3",
    "KEY_KP0",
    "KEY_KPDOT",
    "KEY_ZENKAKUHANKAKU",
    "KEY_102ND",
    "KEY_F11",
    "KEY_F12",
    "KEY_RO",
    "KEY_KATAKANA",
    "KEY_HIRAGANA",
    "KEY_HENKAN",
    "KEY_KATAKANAHIRAGANA",
    "KEY_MUHENKAN",
    "KEY_KPJPCOMMA",
    "KEY_KPENTER",
    "KEY_RIGHTCTRL",
    "KEY_KPSLASH",
    "KEY_SYSRQ",
    "KEY_RIGHTALT",
    "KEY_LINEFEED",
    "KEY_HOME",
    "KEY_UP",
    "KEY_PAGEUP",
    "KEY_LEFT",
    "KEY_RIGHT",
    "KEY_END",
    "KEY_DOWN",
    "KEY_PAGEDOWN",
    "KEY_INSERT",
    "KEY_DELETE",
    "KEY_MACRO",
    "KEY_MUTE",
    "KEY_VOLUMEDOWN",
    "KEY_VOLUMEUP",
    "KEY_POWER",
    "KEY_KPEQUAL",
    "KEY_KPPLUSMINUS",
    "KEY_PAUSE",
    "KEY_SCALE",
    "KEY_KPCOMMA",
    "KEY_HANGEUL",
    "KEY_HANGUEL",
    "KEY_HANJA",
    "KEY_YEN",
    "KEY_LEFTMETA",
    "KEY_RIGHTMETA",
    "KEY_COMPOSE",
    "KEY_STOP",
    "KEY_AGAIN",
    "KEY_PROPS",
    "KEY_UNDO",
    "KEY_FRONT",
    "KEY_COPY",
    "KEY_OPEN",
    "KEY_PASTE",
    "KEY_FIND",
    "KEY_CUT",
    "KEY_HELP",
    "KEY_MENU",
    "KEY_CALC",
    "KEY_SETUP",
    "KEY_SLEEP",
    "KEY_WAKEUP",
    "KEY_FILE",
    "KEY_SENDFILE",
    "KEY_DELETEFILE",
    "KEY_XFER",
    "KEY_PROG1",
    "KEY_PROG2",
    "KEY_WWW",
    "KEY_MSDOS",
    "KEY_COFFEE",
    "KEY_SCREENLOCK",
    "KEY_ROTATE_DISPLAY",
    "KEY_DIRECTION",
    "KEY_CYCLEWINDOWS",
    "KEY_MAIL",
    "KEY_BOOKMARKS",
    "KEY_COMPUTER",
    "KEY_BACK",
    "KEY_FORWARD",
    "KEY_CLOSECD",
    "KEY_EJECTCD",
    "KEY_EJECTCLOSECD",
    "KEY_NEXTSONG",
    "KEY_PLAYPAUSE",
    "KEY_PREVIOUSSONG",
    "KEY_STOPCD",
    "KEY_RECORD",
    "KEY_REWIND",
    "KEY_PHONE",
    "KEY_ISO",
    "KEY_CONFIG",
    "KEY_HOMEPAGE",
    "KEY_REFRESH",
    "KEY_EXIT",
    "KEY_MOVE",
    "KEY_EDIT",
    "KEY_SCROLLUP",
    "KEY_SCROLLDOWN",
    "KEY_KPLEFTPAREN",
    "KEY_KPRIGHTPAREN",
    "KEY_NEW",
    "KEY_REDO",
    "KEY_F13",
    "KEY_F14",
    "KEY_F15",
    "KEY_F16",
    "KEY_F17",
    "KEY_F18",
    "KEY_F19",
    "KEY_F20",
    "KEY_F21",
    "KEY_F22",
    "KEY_F23",
    "KEY_F24",
    "KEY_PLAYCD",
    "KEY_PAUSECD",
    "KEY_PROG3",
    "KEY_PROG4",
    "KEY_DASHBOARD",
    "KEY_SUSPEND",
    "KEY_CLOSE",
    "KEY_PLAY",
    "KEY_FASTFORWARD",
    "KEY_BASSBOOST",
    "KEY_PRINT",
    "KEY_HP",
    "KEY_CAMERA",
    "KEY_SOUND",
    "KEY_QUESTION",
    "KEY_EMAIL",
    "KEY_CHAT",
    "KEY_SEARCH",
    "KEY_CONNECT",
    "KEY_FINANCE",
    "KEY_SPORT",
    "KEY_SHOP",
    "KEY_ALTERASE",
    "KEY_CANCEL",
    "KEY_BRIGHTNESSDOWN",
    "KEY_BRIGHTNESSUP",
    "KEY_MEDIA",
    "KEY_SWITCHVIDEOMODE",
    "KEY_KBDILLUMTOGGLE",
    "KEY_KBDILLUMDOWN",
    "KEY_KBDILLUMUP",
    "KEY_SEND",
    "KEY_REPLY",
    "KEY_FORWARDMAIL",
    "KEY_SAVE",
    "KEY_DOCUMENTS",
    "KEY_BATTERY",
    "KEY_BLUETOOTH",
    "KEY_WLAN",
    "KEY_UWB",
    "KEY_UNKNOWN",
    "KEY_VIDEO_NEXT",
    "KEY_VIDEO_PREV",
    "KEY_BRIGHTNESS_CYCLE",
    "KEY_BRIGHTNESS_ZERO",
    "KEY_DISPLAY_OFF",
    "KEY_WIMAX",
    "KEY_RFKILL",
    "KEY_MICMUTE",
    "BTN_MISC",
    "BTN_0",
    "BTN_1",
    "BTN_2",
    "BTN_3",
    "BTN_4",
    "BTN_5",
    "BTN_6",
    "BTN_7",
    "BTN_8",
    "BTN_9",
    "BTN_LEFT",
    "BTN_RIGHT",
    "BTN_MIDDLE",
    "BTN_SIDE",
    "BTN_EXTRA",
    "BTN_FORWARD",
    "BTN_BACK",
    "BTN_TASK",
    "BTN_TRIGGER",
    "BTN_THUMB",
    "BTN_THUMB2",
    "BTN_TOP",
    "BTN_TOP2",
    "BTN_PINKIE",
    "BTN_BASE",
    "BTN_BASE2",
    "BTN_BASE3",
    "BTN_BASE4",
    "BTN_BASE5",
    "BTN_BASE6",
    "BTN_DEAD",
    "BTN_A",
    "BTN_B",
    "BTN_C",
    "BTN_X",
    "BTN_Y",
    "BTN_Z",
    "BTN_TL",
    "BTN_TR",
    "BTN_TL2",
    "BTN_TR2",
    "BTN_SELECT",
    "BTN_START",
    "BTN_MODE",
    "BTN_THUMBL",
    "BTN_THUMBR",
    "BTN_DIGI",
    "BTN_TOOL_PEN",
    "BTN_TOOL_RUBBER",
    "BTN_TOOL_BRUSH",
    "BTN_TOOL_PENCIL",
    "BTN_TOOL_AIRBRUSH",
    "BTN_TOOL_FINGER",
    "BTN_TOOL_MOUSE",
    "BTN_TOOL_LENS",
    "BTN_TOOL_QUINTTAP",
    "BTN_STYLUS3",
    "BTN_TOUCH",
    "BTN_STYLUS",
    "BTN_STYLUS2",
    "BTN_TOOL_DOUBLETAP",
    "BTN_TOOL_TRIPLETAP",
    "BTN_TOOL_QUADTAP",
    "BTN_WHEEL",
    "BTN_GEAR_DOWN",
    "BTN_GEAR_UP",
    "KEY_OK",
    "KEY_SELECT",
    "KEY_GOTO",
    "KEY_CLEAR",
    "KEY_POWER2",
    "KEY_OPTION",
    "KEY_INFO",
    "KEY_TIME",
    "KEY_VENDOR",
    "KEY_ARCHIVE",
    "KEY_PROGRAM",
    "KEY_CHANNEL",
    "KEY_FAVORITES",
    "KEY_EPG",
    "KEY_PVR",
    "KEY_MHP",
    "KEY_LANGUAGE",
    "KEY_TITLE",
    "KEY_SUBTITLE",
    "KEY_ANGLE",
    "KEY_FULL_SCREEN",
    "KEY_ZOOM",
    "KEY_MODE",
    "KEY_KEYBOARD",
    "KEY_ASPECT_RATIO",
    "KEY_SCREEN",
    "KEY_PC",
    "KEY_TV",
    "KEY_TV2",
    "KEY_VCR",
    "KEY_VCR2",
    "KEY_SAT",
    "KEY_SAT2",
    "KEY_CD",
    "KEY_TAPE",
    "KEY_RADIO",
    "KEY_TUNER",
    "KEY_PLAYER",
    "KEY_TEXT",
    "KEY_DVD",
    "KEY_AUX",
    "KEY_MP3",
    "KEY_AUDIO",
    "KEY_VIDEO",
    "KEY_DIRECTORY",
    "KEY_LIST",
    "KEY_MEMO",
    "KEY_CALENDAR",
    "KEY_RED",
    "KEY_GREEN",
    "KEY_YELLOW",
    "KEY_BLUE",
    "KEY_CHANNELUP",
    "KEY_CHANNELDOWN",
    "KEY_FIRST",
    "KEY_LAST",
    "KEY_AB",
    "KEY_NEXT",
    "KEY_RESTART",
    "KEY_SLOW",
    "KEY_SHUFFLE",
    "KEY_BREAK",
    "KEY_PREVIOUS",
    "KEY_DIGITS",
    "KEY_TEEN",
    "KEY_TWEN",
    "KEY_VIDEOPHONE",
    "KEY_GAMES",
    "KEY_ZOOMIN",
    "KEY_ZOOMOUT",
    "KEY_ZOOMRESET",
    "KEY_WORDPROCESSOR",
    "KEY_EDITOR",
    "KEY_SPREADSHEET",
    "KEY_GRAPHICSEDITOR",
    "KEY_PRESENTATION",
    "KEY_DATABASE",
    "KEY_NEWS",
    "KEY_VOICEMAIL",
    "KEY_ADDRESSBOOK",
    "KEY_MESSENGER",
    "KEY_DISPLAYTOGGLE",
    "KEY_BRIGHTNESS_TOGGLE",
    "KEY_SPELLCHECK",
    "KEY_LOGOFF",
    "KEY_DOLLAR",
    "KEY_EURO",
    "KEY_FRAMEBACK",
    "KEY_FRAMEFORWARD",
    "KEY_CONTEXT_MENU",
    "KEY_MEDIA_REPEAT",
    "KEY_10CHANNELSUP",
    "KEY_10CHANNELSDOWN",
    "KEY_IMAGES",
    "KEY_DEL_EOL",
    "KEY_DEL_EOS",
    "KEY_INS_LINE",
    "KEY_DEL_LINE",
    "KEY_FN",
    "KEY_FN_ESC",
    "KEY_FN_F1",
    "KEY_FN_F2",
    "KEY_FN_F3",
    "KEY_FN_F4",
    "KEY_FN_F5",
    "KEY_FN_F6",
    "KEY_FN_F7",
    "KEY_FN_F8",
    "KEY_FN_F9",
    "KEY_FN_F10",
    "KEY_FN_F11",
    "KEY_FN_F12",
    "KEY_FN_1",
    "KEY_FN_2",
    "KEY_FN_D",
    "KEY_FN_E",
    "KEY_FN_F",
    "KEY_FN_S",
    "KEY_FN_B",
    "KEY_BRL_DOT1",
    "KEY_BRL_DOT2",
    "KEY_BRL_DOT3",
    "KEY_BRL_DOT4",
    "KEY_BRL_DOT5",
    "KEY_BRL_DOT6",
    "KEY_BRL_DOT7",
    "KEY_BRL_DOT8",
    "KEY_BRL_DOT9",
    "KEY_BRL_DOT10",
    "KEY_NUMERIC_0",
    "KEY_NUMERIC_1",
    "KEY_NUMERIC_2",
    "KEY_NUMERIC_3",
    "KEY_NUMERIC_4",
    "KEY_NUMERIC_5",
    "KEY_NUMERIC_6",
    "KEY_NUMERIC_7",
    "KEY_NUMERIC_8",
    "KEY_NUMERIC_9",
    "KEY_NUMERIC_STAR",
    "KEY_NUMERIC_POUND",
    "KEY_CAMERA_FOCUS",
    "KEY_WPS_BUTTON",
    "KEY_TOUCHPAD_TOGGLE",
    "KEY_TOUCHPAD_ON",
    "KEY_TOUCHPAD_OFF",
    "KEY_CAMERA_ZOOMIN",
    "KEY_CAMERA_ZOOMOUT",
    "KEY_CAMERA_UP",
    "KEY_CAMERA_DOWN",
    "KEY_CAMERA_LEFT",
    "KEY_CAMERA_RIGHT",
    "KEY_ATTENDANT_ON",
    "KEY_ATTENDANT_OFF",
    "KEY_ATTENDANT_TOGGLE",
    "KEY_LIGHTS_TOGGLE",
    "BTN_DPAD_UP",
    "BTN_DPAD_DOWN",
    "BTN_DPAD_LEFT",
    "BTN_DPAD_RIGHT",
    "KEY_ALS_TOGGLE",
    "KEY_ROTATE_LOCK_TOGGLE",
    "KEY_BUTTONCONFIG",
    "KEY_TASKMANAGER",
    "KEY_JOURNAL",
    "KEY_CONTROLPANEL",
    "KEY_APPSELECT",
    "KEY_SCREENSAVER",
    "KEY_VOICECOMMAND",
    "KEY_ASSISTANT",
    "KEY_KBD_LAYOUT_NEXT",
    "KEY_BRIGHTNESS_MIN",
    "KEY_BRIGHTNESS_MAX",
    "KEY_KBDINPUTASSIST_PREV",
    "KEY_KBDINPUTASSIST_NEXT",
    "KEY_KBDINPUTASSIST_PREVGROUP",
    "KEY_KBDINPUTASSIST_NEXTGROUP",
    "KEY_KBDINPUTASSIST_ACCEPT",
    "KEY_KBDINPUTASSIST_CANCEL",
    "KEY_RIGHT_UP",
    "KEY_RIGHT_DOWN",
    "KEY_LEFT_UP",
    "KEY_LEFT_DOWN",
    "KEY_ROOT_MENU",
    "KEY_MEDIA_TOP_MENU",
    "KEY_NUMERIC_11",
    "KEY_NUMERIC_12",
    "KEY_AUDIO_DESC",
    "KEY_3D_MODE",
    "KEY_NEXT_FAVORITE",
    "KEY_STOP_RECORD",
    "KEY_PAUSE_RECORD",
    "KEY_VOD",
    "KEY_UNMUTE",
    "KEY_FASTREVERSE",
    "KEY_SLOWREVERSE",
    "KEY_DATA",
    "KEY_ONSCREEN_KEYBOARD",
    "KEY_PRIVACY_SCREEN_TOGGLE",
    "KEY_SELECTIVE_SCREENSHOT",
    "KEY_NEXT_ELEMENT",
    "KEY_PREVIOUS_ELEMENT",
    "KEY_AUTOPILOT_ENGAGE_TOGGLE",
    "KEY_MARK_WAYPOINT",
    "KEY_SOS",
    "KEY_NAV_CHART",
    "KEY_FISHING_CHART",
    "KEY_SINGLE_RANGE_RADAR",
    "KEY_DUAL_RANGE_RADAR",
    "KEY_RADAR_OVERLAY",
    "KEY_TRADITIONAL_SONAR",
    "KEY_CLEARVU_SONAR",
    "KEY_SIDEVU_SONAR",
    "KEY_NAV_INFO",
    "KEY_BRIGHTNESS_MENU",
    "KEY_MACRO1",
    "KEY_MACRO2",
    "KEY_MACRO3",
    "KEY_MACRO4",
    "KEY_MACRO5",
    "KEY_MACRO6",
    "KEY_MACRO7",
    "KEY_MACRO8",
    "KEY_MACRO9",
    "KEY_MACRO10",
    "KEY_MACRO11",
    "KEY_MACRO12",
    "KEY_MACRO13",
    "KEY_MACRO14",
    "KEY_MACRO15",
    "KEY_MACRO16",
    "KEY_MACRO17",
    "KEY_MACRO18",
    "KEY_MACRO19",
    "KEY_MACRO20",
    "KEY_MACRO21",
    "KEY_MACRO22",
    "KEY_MACRO23",
    "KEY_MACRO24",
    "KEY_MACRO25",
    "KEY_MACRO26",
    "KEY_MACRO27",
    "KEY_MACRO28",
    "KEY_MACRO29",
    "KEY_MACRO30",
    "KEY_MACRO_RECORD_START",
    "KEY_MACRO_RECORD_STOP",
    "KEY_MACRO_PRESET_CYCLE",
    "KEY_MACRO_PRESET1",
    "KEY_MACRO_PRESET2",
    "KEY_MACRO_PRESET3",
    "KEY_KBD_LCD_MENU1",
    "KEY_KBD_LCD_MENU2",
    "KEY_KBD_LCD_MENU3",
    "KEY_KBD_LCD_MENU4",
    "KEY_KBD_LCD_MENU5",
    "BTN_TRIGGER_HAPPY",
    "BTN_TRIGGER_HAPPY1",
    "BTN_TRIGGER_HAPPY2",
    "BTN_TRIGGER_HAPPY3",
    "BTN_TRIGGER_HAPPY4",
    "BTN_TRIGGER_HAPPY5",
    "BTN_TRIGGER_HAPPY6",
    "BTN_TRIGGER_HAPPY7",
    "BTN_TRIGGER_HAPPY8",
    "BTN_TRIGGER_HAPPY9",
    "BTN_TRIGGER_HAPPY10",
    "BTN_TRIGGER_HAPPY11",
    "BTN_TRIGGER_HAPPY12",
    "BTN_TRIGGER_HAPPY13",
    "BTN_TRIGGER_HAPPY14",
    "BTN_TRIGGER_HAPPY15",
    "BTN_TRIGGER_HAPPY16",
    "BTN_TRIGGER_HAPPY17",
    "BTN_TRIGGER_HAPPY18",
    "BTN_TRIGGER_HAPPY19",
    "BTN_TRIGGER_HAPPY20",
    "BTN_TRIGGER_HAPPY21",
    "BTN_TRIGGER_HAPPY22",
    "BTN_TRIGGER_HAPPY23",
    "BTN_TRIGGER_HAPPY24",
    "BTN_TRIGGER_HAPPY25",
    "BTN_TRIGGER_HAPPY26",
    "BTN_TRIGGER_HAPPY27",
    "BTN_TRIGGER_HAPPY28",
    "BTN_TRIGGER_HAPPY29",
    "BTN_TRIGGER_HAPPY30",
    "BTN_TRIGGER_HAPPY31",
    "BTN_TRIGGER_HAPPY32",
    "BTN_TRIGGER_HAPPY33",
    "BTN_TRIGGER_HAPPY34",
    "BTN_TRIGGER_HAPPY35",
    "BTN_TRIGGER_HAPPY36",
    "BTN_TRIGGER_HAPPY37",
    "BTN_TRIGGER_HAPPY38",
    "BTN_TRIGGER_HAPPY39",
    "BTN_TRIGGER_HAPPY40",
    "REL_X",
    "REL_Y",
    "REL_Z",
    "REL_RX",
    "REL_RY",
    "REL_RZ",
    "REL_HWHEEL",
    "REL_DIAL",
    "REL_WHEEL",
    "REL_MISC",
    "REL_RESERVED",
    "REL_WHEEL_HI_RES",
    "REL_HWHEEL_HI_RES",
    "ABS_X",
    "ABS_Y",
    "ABS_Z",
    "ABS_RX",
    "ABS_RY",
    "ABS_RZ",
    "ABS_THROTTLE",
    "ABS_RUDDER",
    "ABS_WHEEL",
    "ABS_GAS",
    "ABS_BRAKE",
    "ABS_HAT0X",
    "ABS_HAT0Y",
    "ABS_HAT1X",
    "ABS_HAT1Y",
    "ABS_HAT2X",
    "ABS_HAT2Y",
    "ABS_HAT3X",
    "ABS_HAT3Y",
    "ABS_PRESSURE",
    "ABS_DISTANCE",
    "ABS_TILT_X",
    "ABS_TILT_Y",
    "ABS_TOOL_WIDTH",
    "ABS_VOLUME",
    "ABS_PROFILE",
    "ABS_MISC",
    "ABS_RESERVED",
    "ABS_MT_SLOT",
    "ABS_MT_TOUCH_MAJOR",
    "ABS_MT_TOUCH_MINOR",
    "ABS_MT_WIDTH_MAJOR",
    "ABS_MT_WIDTH_MINOR",
    "ABS_MT_ORIENTATION",
    "ABS_MT_POSITION_X",
    "ABS_MT_POSITION_Y",
    "ABS_MT_TOOL_TYPE",
    "ABS_MT_BLOB_ID",
    "ABS_MT_TRACKING_ID",
    "ABS_MT_PRESSURE",
    "ABS_MT_DISTANCE",
    "ABS_MT_TOOL_X",
    "ABS_MT_TOOL_Y",
    "ABS_MAX",
    "ABS_CNT",
    "SW_LID",
    "SW_TABLET_MODE",
    "SW_HEADPHONE_INSERT",
    "SW_RFKILL_ALL",
    "SW_RADIO",
    "SW_MICROPHONE_INSERT",
    "SW_DOCK",
    "SW_LINEOUT_INSERT",
    "SW_JACK_PHYSICAL_INSERT",
    "SW_VIDEOOUT_INSERT",
    "SW_CAMERA_LENS_COVER",
    "SW_KEYPAD_SLIDE",
    "SW_FRONT_PROXIMITY",
    "SW_ROTATE_LOCK",
    "SW_LINEIN_INSERT",
    "SW_MUTE_DEVICE",
    "SW_PEN_INSERTED",
    "SW_MACHINE_COVER",
    "SW_MAX",
    "SW_CNT",
    "MSC_SERIAL",
    "MSC_PULSELED",
    "MSC_GESTURE",
    "MSC_RAW",
    "MSC_SCAN",
    "MSC_TIMESTAMP",
    "MSC_MAX",
    "MSC_CNT",
    "LED_NUML",
    "LED_CAPSL",
    "LED_SCROLLL",
    "LED_COMPOSE",
    "LED_KANA",
    "LED_SLEEP",
    "LED_SUSPEND",
    "LED_MUTE",
    "LED_MISC",
    "LED_MAIL",
    "LED_CHARGING",
    "LED_MAX",
    "LED_CNT",
    "REP_DELAY",
    "REP_PERIOD",
    "REP_MAX",
    "REP_CNT",
    "SND_CLICK",
    "SND_BELL",
    "SND_TONE",
    "SND_MAX",
    "SND_CNT",
]


KEY_RESERVED = 0
KEY_ESC = 1
KEY_1 = 2
KEY_2 = 3
KEY_3 = 4
KEY_4 = 5
KEY_5 = 6
KEY_6 = 7
KEY_7 = 8
KEY_8 = 9
KEY_9 = 10
KEY_0 = 11
KEY_MINUS = 12
KEY_EQUAL = 13
KEY_BACKSPACE = 14
KEY_TAB = 15
KEY_Q = 16
KEY_W = 17
KEY_E = 18
KEY_R = 19
KEY_T = 20
KEY_Y = 21
KEY_U = 22
KEY_I = 23
KEY_O = 24
KEY_P = 25
KEY_LEFTBRACE = 26
KEY_RIGHTBRACE = 27
KEY_ENTER = 28
KEY_LEFTCTRL = 29
KEY_A = 30
KEY_S = 31
KEY_D = 32
KEY_F = 33
KEY_G = 34
KEY_H = 35
KEY_J = 36
KEY_K = 37
KEY_L = 38
KEY_SEMICOLON = 39
KEY_APOSTROPHE = 40
KEY_GRAVE = 41
KEY_LEFTSHIFT = 42
KEY_BACKSLASH = 43
KEY_Z = 44
KEY_X = 45
KEY_C = 46
KEY_V = 47
KEY_B = 48
KEY_N = 49
KEY_M = 50
KEY_COMMA = 51
KEY_DOT = 52
KEY_SLASH = 53
KEY_RIGHTSHIFT = 54
KEY_KPASTERISK = 55
KEY_LEFTALT = 56
KEY_SPACE = 57
KEY_CAPSLOCK = 58
KEY_F1 = 59
KEY_F2 = 60
KEY_F3 = 61
KEY_F4 = 62
KEY_F5 = 63
KEY_F6 = 64
KEY_F7 = 65
KEY_F8 = 66
KEY_F9 = 67
KEY_F10 = 68
KEY_NUMLOCK = 69
KEY_SCROLLLOCK = 70
KEY_KP7 = 71
KEY_KP8 = 72
KEY_KP9 = 73
KEY_KPMINUS = 74
KEY_KP4 = 75
KEY_KP5 = 76
KEY_KP6 = 77
KEY_KPPLUS = 78
KEY_KP1 = 79
KEY_KP2 = 80
KEY_KP3 = 81
KEY_KP0 = 82
KEY_KPDOT = 83

KEY_ZENKAKUHANKAKU = 85
KEY_102ND = 86
KEY_F11 = 87
KEY_F12 = 88
KEY_RO = 89
KEY_KATAKANA = 90
KEY_HIRAGANA = 91
KEY_HENKAN = 92
KEY_KATAKANAHIRAGANA = 93
KEY_MUHENKAN = 94
KEY_KPJPCOMMA = 95
KEY_KPENTER = 96
KEY_RIGHTCTRL = 97
KEY_KPSLASH = 98
KEY_SYSRQ = 99
KEY_RIGHTALT = 100
KEY_LINEFEED = 101
KEY_HOME = 102
KEY_UP = 103
KEY_PAGEUP = 104
KEY_LEFT = 105
KEY_RIGHT = 106
KEY_END = 107
KEY_DOWN = 108
KEY_PAGEDOWN = 109
KEY_INSERT = 110
KEY_DELETE = 111
KEY_MACRO = 112
KEY_MUTE = 113
KEY_VOLUMEDOWN = 114
KEY_VOLUMEUP = 115
KEY_POWER = 116
KEY_KPEQUAL = 117
KEY_KPPLUSMINUS = 118
KEY_PAUSE = 119
KEY_SCALE = 120

KEY_KPCOMMA = 121
KEY_HANGEUL = 122
KEY_HANGUEL = KEY_HANGEUL
KEY_HANJA = 123
KEY_YEN = 124
KEY_LEFTMETA = 125
KEY_RIGHTMETA = 126
KEY_COMPOSE = 127

KEY_STOP = 128
KEY_AGAIN = 129
KEY_PROPS = 130
KEY_UNDO = 131
KEY_FRONT = 132
KEY_COPY = 133
KEY_OPEN = 134
KEY_PASTE = 135
KEY_FIND = 136
KEY_CUT = 137
KEY_HELP = 138
KEY_MENU = 139
KEY_CALC = 140
KEY_SETUP = 141
KEY_SLEEP = 142
KEY_WAKEUP = 143
KEY_FILE = 144
KEY_SENDFILE = 145
KEY_DELETEFILE = 146
KEY_XFER = 147
KEY_PROG1 = 148
KEY_PROG2 = 149
KEY_WWW = 150  # AL Internet Browser
KEY_MSDOS = 151
KEY_COFFEE = 152  # AL Terminal Lock/Screensaver
KEY_SCREENLOCK = KEY_COFFEE
KEY_ROTATE_DISPLAY = 153  # Display orientation for e.g. tablets
KEY_DIRECTION = KEY_ROTATE_DISPLAY
KEY_CYCLEWINDOWS = 154
KEY_MAIL = 155
KEY_BOOKMARKS = 156  # AC Bookmarks
KEY_COMPUTER = 157
KEY_BACK = 158  # AC Back
KEY_FORWARD = 159  # AC Forward
KEY_CLOSECD = 160
KEY_EJECTCD = 161
KEY_EJECTCLOSECD = 162
KEY_NEXTSONG = 163
KEY_PLAYPAUSE = 164
KEY_PREVIOUSSONG = 165
KEY_STOPCD = 166
KEY_RECORD = 167
KEY_REWIND = 168
KEY_PHONE = 169  # Media Select Telephone
KEY_ISO = 170
KEY_CONFIG = 171  # AL Consumer Control Configuration
KEY_HOMEPAGE = 172  # AC Home
KEY_REFRESH = 173  # AC Refresh
KEY_EXIT = 174  # AC Exit
KEY_MOVE = 175
KEY_EDIT = 176
KEY_SCROLLUP = 177
KEY_SCROLLDOWN = 178
KEY_KPLEFTPAREN = 179
KEY_KPRIGHTPAREN = 180
KEY_NEW = 181  # AC New
KEY_REDO = 182  # AC Redo/Repeat

KEY_F13 = 183
KEY_F14 = 184
KEY_F15 = 185
KEY_F16 = 186
KEY_F17 = 187
KEY_F18 = 188
KEY_F19 = 189
KEY_F20 = 190
KEY_F21 = 191
KEY_F22 = 192
KEY_F23 = 193
KEY_F24 = 194

# Keyboard Keys
KEY_PLAYCD = 200
KEY_PAUSECD = 201
KEY_PROG3 = 202
KEY_PROG4 = 203
KEY_ALL_APPLICATIONS = 204  # AC Desktop Show All Applications
KEY_DASHBOARD = KEY_ALL_APPLICATIONS
KEY_SUSPEND = 205
KEY_CLOSE = 206  # AC Close
KEY_PLAY = 207
KEY_FASTFORWARD = 208
KEY_BASSBOOST = 209
KEY_PRINT = 210  # AC Print
KEY_HP = 211
KEY_CAMERA = 212
KEY_SOUND = 213
KEY_QUESTION = 214
KEY_EMAIL = 215
KEY_CHAT = 216
KEY_SEARCH = 217
KEY_CONNECT = 218
KEY_FINANCE = 219  # AL Checkbook/Finance
KEY_SPORT = 220
KEY_SHOP = 221
KEY_ALTERASE = 222
KEY_CANCEL = 223  # AC Cancel
KEY_BRIGHTNESSDOWN = 224
KEY_BRIGHTNESSUP = 225
KEY_MEDIA = 226

KEY_SWITCHVIDEOMODE = (
    227  # Cycle between available video outputs (Monitor/LCD/TV-out/etc)
)
KEY_KBDILLUMTOGGLE = 228
KEY_KBDILLUMDOWN = 229
KEY_KBDILLUMUP = 230

KEY_SEND = 231  # AC Send
KEY_REPLY = 232  # AC Reply
KEY_FORWARDMAIL = 233  # AC Forward Msg
KEY_SAVE = 234  # AC Save
KEY_DOCUMENTS = 235

KEY_BATTERY = 236

KEY_BLUETOOTH = 237
KEY_WLAN = 238
KEY_UWB = 239

KEY_UNKNOWN = 240

KEY_VIDEO_NEXT = 241  # Drive next video source
KEY_VIDEO_PREV = 242  # Drive previous video source
KEY_BRIGHTNESS_CYCLE = 243  # Brightness up, after max is min
KEY_BRIGHTNESS_AUTO = (
    244  # Set Auto Brightness: manual brightness control is off, rely on ambient
)
KEY_BRIGHTNESS_ZERO = KEY_BRIGHTNESS_AUTO
KEY_DISPLAY_OFF = 245  # Display device to off state

KEY_WWAN = 246  # Wireless WAN (LTE, UMTS, GSM, etc.)
KEY_WIMAX = KEY_WWAN
KEY_RFKILL = 247  # Key that controls all radios

KEY_MICMUTE = 248  # Mute / unmute the microphone

# Code 255 is reserved for special needs of the AT keyboard driver

# Mouse Buttons
BTN_MISC = 0x100
BTN_0 = 0x100
BTN_1 = 0x101
BTN_2 = 0x102
BTN_3 = 0x103
BTN_4 = 0x104
BTN_5 = 0x105
BTN_6 = 0x106
BTN_7 = 0x107
BTN_8 = 0x108
BTN_9 = 0x109

BTN_MOUSE = 0x110
BTN_LEFT = 0x110
BTN_RIGHT = 0x111
BTN_MIDDLE = 0x112
BTN_SIDE = 0x113
BTN_EXTRA = 0x114
BTN_FORWARD = 0x115
BTN_BACK = 0x116
BTN_TASK = 0x117

BTN_JOYSTICK = 0x120
BTN_TRIGGER = 0x120
BTN_THUMB = 0x121
BTN_THUMB2 = 0x122
BTN_TOP = 0x123
BTN_TOP2 = 0x124
BTN_PINKIE = 0x125
BTN_BASE = 0x126
BTN_BASE2 = 0x127
BTN_BASE3 = 0x128
BTN_BASE4 = 0x129
BTN_BASE5 = 0x12A
BTN_BASE6 = 0x12B
BTN_DEAD = 0x12F

# Gamepad Buttons
BTN_GAMEPAD = 0x130
BTN_SOUTH = BTN_GAMEPAD
BTN_A = BTN_SOUTH
BTN_EAST = 0x131
BTN_B = BTN_EAST
BTN_C = 0x132
BTN_NORTH = 0x133
BTN_X = BTN_NORTH
BTN_WEST = 0x134
BTN_Y = BTN_WEST
BTN_Z = 0x135
BTN_TL = 0x136
BTN_TR = 0x137
BTN_TL2 = 0x138
BTN_TR2 = 0x139
BTN_SELECT = 0x13A
BTN_START = 0x13B
BTN_MODE = 0x13C
BTN_THUMBL = 0x13D
BTN_THUMBR = 0x13E

# Digi Buttons (Pen Input)
BTN_DIGI = 0x140
BTN_TOOL_PEN = 0x140
BTN_TOOL_RUBBER = 0x141
BTN_TOOL_BRUSH = 0x142
BTN_TOOL_PENCIL = 0x143
BTN_TOOL_AIRBRUSH = 0x144
BTN_TOOL_FINGER = 0x145
BTN_TOOL_MOUSE = 0x146
BTN_TOOL_LENS = 0x147
BTN_TOOL_QUINTTAP = 0x148  # Five fingers on trackpad
BTN_STYLUS3 = 0x149
BTN_TOUCH = 0x14A
BTN_STYLUS = 0x14B
BTN_STYLUS2 = 0x14C
BTN_TOOL_DOUBLETAP = 0x14D
BTN_TOOL_TRIPLETAP = 0x14E
BTN_TOOL_QUADTAP = 0x14F  # Four fingers on trackpad

# Wheel Buttons
BTN_WHEEL = 0x150
BTN_GEAR_DOWN = 0x150
BTN_GEAR_UP = 0x151

# Media Keys
KEY_OK = 0x160
KEY_SELECT = 0x161
KEY_GOTO = 0x162
KEY_CLEAR = 0x163
KEY_POWER2 = 0x164
KEY_OPTION = 0x165
KEY_INFO = 0x166  # AL OEM Features/Tips/Tutorial
KEY_TIME = 0x167
KEY_VENDOR = 0x168
KEY_ARCHIVE = 0x169
KEY_PROGRAM = 0x16A  # Media Select Program Guide
KEY_CHANNEL = 0x16B
KEY_FAVORITES = 0x16C
KEY_EPG = 0x16D
KEY_PVR = 0x16E  # Media Select Home
KEY_MHP = 0x16F
KEY_LANGUAGE = 0x170
KEY_TITLE = 0x171
KEY_SUBTITLE = 0x172
KEY_ANGLE = 0x173
KEY_FULL_SCREEN = 0x174  # AC View Toggle
KEY_ZOOM = KEY_FULL_SCREEN
KEY_MODE = 0x175
KEY_KEYBOARD = 0x176
KEY_ASPECT_RATIO = 0x177  # HUTRR37: Aspect
KEY_SCREEN = KEY_ASPECT_RATIO
KEY_PC = 0x178  # Media Select Computer
KEY_TV = 0x179  # Media Select TV
KEY_TV2 = 0x17A  # Media Select Cable
KEY_VCR = 0x17B  # Media Select VCR
KEY_VCR2 = 0x17C  # VCR Plus
KEY_SAT = 0x17D  # Media Select Satellite
KEY_SAT2 = 0x17E
KEY_CD = 0x17F  # Media Select CD
KEY_TAPE = 0x180  # Media Select Tape
KEY_RADIO = 0x181
KEY_TUNER = 0x182  # Media Select Tuner
KEY_PLAYER = 0x183
KEY_TEXT = 0x184
KEY_DVD = 0x185  # Media Select DVD
KEY_AUX = 0x186
KEY_MP3 = 0x187
KEY_AUDIO = 0x188  # AL Audio Browser
KEY_VIDEO = 0x189  # AL Movie Browser
KEY_DIRECTORY = 0x18A
KEY_LIST = 0x18B
KEY_MEMO = 0x18C  # Media Select Messages
KEY_CALENDAR = 0x18D
KEY_RED = 0x18E
KEY_GREEN = 0x18F
KEY_YELLOW = 0x190
KEY_BLUE = 0x191
KEY_CHANNELUP = 0x192  # Channel Increment
KEY_CHANNELDOWN = 0x193  # Channel Decrement
KEY_FIRST = 0x194
KEY_LAST = 0x195  # Recall Last
KEY_AB = 0x196
KEY_NEXT = 0x197
KEY_RESTART = 0x198
KEY_SLOW = 0x199
KEY_SHUFFLE = 0x19A
KEY_BREAK = 0x19B
KEY_PREVIOUS = 0x19C
KEY_DIGITS = 0x19D
KEY_TEEN = 0x19E
KEY_TWEN = 0x19F
KEY_VIDEOPHONE = 0x1A0  # Media Select Video Phone
KEY_GAMES = 0x1A1  # Media Select Games
KEY_ZOOMIN = 0x1A2  # AC Zoom In
KEY_ZOOMOUT = 0x1A3  # AC Zoom Out
KEY_ZOOMRESET = 0x1A4  # AC Zoom
KEY_WORDPROCESSOR = 0x1A5  # AL Word Processor
KEY_EDITOR = 0x1A6  # AL Text Editor
KEY_SPREADSHEET = 0x1A7  # AL Spreadsheet
KEY_GRAPHICSEDITOR = 0x1A8  # AL Graphics Editor
KEY_PRESENTATION = 0x1A9  # AL Presentation App
KEY_DATABASE = 0x1AA  # AL Database App
KEY_NEWS = 0x1AB  # AL Newsreader
KEY_VOICEMAIL = 0x1AC  # AL Voicemail
KEY_ADDRESSBOOK = 0x1AD  # AL Contacts/Address Book
KEY_MESSENGER = 0x1AE  # AL Instant Messaging
KEY_DISPLAYTOGGLE = 0x1AF  # Turn display (LCD) on and off
KEY_BRIGHTNESS_TOGGLE = KEY_DISPLAYTOGGLE
KEY_SPELLCHECK = 0x1B0  # AL Spell Check
KEY_LOGOFF = 0x1B1  # AL Logoff

# Currency Keys
KEY_DOLLAR = 0x1B2
KEY_EURO = 0x1B3

# Media Control Buttons
KEY_FRAMEBACK = 0x1B4  # Consumer - transport controls
KEY_FRAMEFORWARD = 0x1B5
KEY_CONTEXT_MENU = 0x1B6  # GenDesc - system context menu
KEY_MEDIA_REPEAT = 0x1B7  # Consumer - transport control
KEY_10CHANNELSUP = 0x1B8  # 10 channels up (10+)
KEY_10CHANNELSDOWN = 0x1B9  # 10 channels down (10-)
KEY_IMAGES = 0x1BA  # AL Image Browser
KEY_NOTIFICATION_CENTER = 0x1BC  # Show/hide the notification center
KEY_PICKUP_PHONE = 0x1BD  # Answer incoming call
KEY_HANGUP_PHONE = 0x1BE  # Decline incoming call

# Delete and Insert Buttons
KEY_DEL_EOL = 0x1C0
KEY_DEL_EOS = 0x1C1
KEY_INS_LINE = 0x1C2
KEY_DEL_LINE = 0x1C3

# Function Keys
KEY_FN = 0x1D0
KEY_FN_ESC = 0x1D1
KEY_FN_F1 = 0x1D2
KEY_FN_F2 = 0x1D3
KEY_FN_F3 = 0x1D4
KEY_FN_F4 = 0x1D5
KEY_FN_F5 = 0x1D6
KEY_FN_F6 = 0x1D7
KEY_FN_F7 = 0x1D8
KEY_FN_F8 = 0x1D9
KEY_FN_F9 = 0x1DA
KEY_FN_F10 = 0x1DB
KEY_FN_F11 = 0x1DC
KEY_FN_F12 = 0x1DD
KEY_FN_1 = 0x1DE
KEY_FN_2 = 0x1DF
KEY_FN_D = 0x1E0
KEY_FN_E = 0x1E1
KEY_FN_F = 0x1E2
KEY_FN_S = 0x1E3
KEY_FN_B = 0x1E4
KEY_FN_RIGHT_SHIFT = 0x1E5

# Braille Buttons
KEY_BRL_DOT1 = 0x1F1
KEY_BRL_DOT2 = 0x1F2
KEY_BRL_DOT3 = 0x1F3
KEY_BRL_DOT4 = 0x1F4
KEY_BRL_DOT5 = 0x1F5
KEY_BRL_DOT6 = 0x1F6
KEY_BRL_DOT7 = 0x1F7
KEY_BRL_DOT8 = 0x1F8
KEY_BRL_DOT9 = 0x1F9
KEY_BRL_DOT10 = 0x1FA

# Numeric Keys (used by phones, remote controls, and other keypads)
KEY_NUMERIC_0 = 0x200
KEY_NUMERIC_1 = 0x201
KEY_NUMERIC_2 = 0x202
KEY_NUMERIC_3 = 0x203
KEY_NUMERIC_4 = 0x204
KEY_NUMERIC_5 = 0x205
KEY_NUMERIC_6 = 0x206
KEY_NUMERIC_7 = 0x207
KEY_NUMERIC_8 = 0x208
KEY_NUMERIC_9 = 0x209
KEY_NUMERIC_STAR = 0x20A
KEY_NUMERIC_POUND = 0x20B
KEY_NUMERIC_A = 0x20C  # Phone key A - HUT Telephony 0xb9
KEY_NUMERIC_B = 0x20D
KEY_NUMERIC_C = 0x20E
KEY_NUMERIC_D = 0x20F

# Camera Keys
KEY_CAMERA_FOCUS = 0x210
KEY_WPS_BUTTON = 0x211  # WiFi Protected Setup key
KEY_TOUCHPAD_TOGGLE = 0x212  # Request switch touchpad on or off
KEY_TOUCHPAD_ON = 0x213
KEY_TOUCHPAD_OFF = 0x214
KEY_CAMERA_ZOOMIN = 0x215
KEY_CAMERA_ZOOMOUT = 0x216
KEY_CAMERA_UP = 0x217
KEY_CAMERA_DOWN = 0x218
KEY_CAMERA_LEFT = 0x219
KEY_CAMERA_RIGHT = 0x21A
KEY_ATTENDANT_ON = 0x21B
KEY_ATTENDANT_OFF = 0x21C
KEY_ATTENDANT_TOGGLE = 0x21D  # Attendant call on or off
KEY_LIGHTS_TOGGLE = 0x21E  # Reading light on or off

# Dpad Buttons
BTN_DPAD_UP = 0x220
BTN_DPAD_DOWN = 0x221
BTN_DPAD_LEFT = 0x222
BTN_DPAD_RIGHT = 0x223

# Additional Special Keys
KEY_ALS_TOGGLE = 0x230  # Ambient light sensor
KEY_ROTATE_LOCK_TOGGLE = 0x231  # Display rotation lock
KEY_BUTTONCONFIG = 0x240  # AL Button Configuration
KEY_TASKMANAGER = 0x241  # AL Task/Project Manager
KEY_JOURNAL = 0x242  # AL Log/Journal/Timecard
KEY_CONTROLPANEL = 0x243  # AL Control Panel
KEY_APPSELECT = 0x244  # AL Select Task/Application
KEY_SCREENSAVER = 0x245  # AL Screen Saver
KEY_VOICECOMMAND = 0x246  # Listening Voice Command
KEY_ASSISTANT = 0x247  # AL Context-aware desktop assistant
KEY_KBD_LAYOUT_NEXT = 0x248  # AC Next Keyboard Layout Select
KEY_EMOJI_PICKER = 0x249  # Show/hide emoji picker (HUTRR101)
KEY_DICTATE = 0x24A  # Start or Stop Voice Dictation Session (HUTRR99)
KEY_CAMERA_ACCESS_ENABLE = (
    0x24B  # Enables programmatic access to camera devices. (HUTRR72)
)
KEY_CAMERA_ACCESS_DISABLE = (
    0x24C  # Disables programmatic access to camera devices. (HUTRR72)
)
KEY_CAMERA_ACCESS_TOGGLE = (
    0x24D  # Toggles the current state of the camera access control. (HUTRR72)
)

KEY_BRIGHTNESS_MIN = 0x250  # Set Brightness to Minimum
KEY_BRIGHTNESS_MAX = 0x251  # Set Brightness to Maximum

KEY_KBDINPUTASSIST_PREV = 0x260
KEY_KBDINPUTASSIST_NEXT = 0x261
KEY_KBDINPUTASSIST_PREVGROUP = 0x262
KEY_KBDINPUTASSIST_NEXTGROUP = 0x263
KEY_KBDINPUTASSIST_ACCEPT = 0x264
KEY_KBDINPUTASSIST_CANCEL = 0x265

# Diagonal movement keys
KEY_RIGHT_UP = 0x266
KEY_RIGHT_DOWN = 0x267
KEY_LEFT_UP = 0x268
KEY_LEFT_DOWN = 0x269

KEY_ROOT_MENU = 0x26A  # Show Device's Root Menu
KEY_MEDIA_TOP_MENU = 0x26B  # Show Top Menu of the Media (e.g. DVD)
KEY_NUMERIC_11 = 0x26C
KEY_NUMERIC_12 = 0x26D

# Toggle Audio Description: refers to an audio service that helps blind and visually impaired consumers understand the action in a program.
# Note: in some countries, this is referred to as "Video Description".
KEY_AUDIO_DESC = 0x26E
KEY_3D_MODE = 0x26F
KEY_NEXT_FAVORITE = 0x270
KEY_STOP_RECORD = 0x271
KEY_PAUSE_RECORD = 0x272
KEY_VOD = 0x273  # Video on Demand
# Keyboard Keys
KEY_UNMUTE = 0x274
KEY_FASTREVERSE = 0x275
KEY_SLOWREVERSE = 0x276
KEY_DATA = 0x277
KEY_ONSCREEN_KEYBOARD = 0x278
KEY_PRIVACY_SCREEN_TOGGLE = 0x279
KEY_SELECTIVE_SCREENSHOT = 0x27A
KEY_NEXT_ELEMENT = 0x27B
KEY_PREVIOUS_ELEMENT = 0x27C
KEY_AUTOPILOT_ENGAGE_TOGGLE = 0x27D
KEY_MARK_WAYPOINT = 0x27E
KEY_SOS = 0x27F
KEY_NAV_CHART = 0x280
KEY_FISHING_CHART = 0x281
KEY_SINGLE_RANGE_RADAR = 0x282
KEY_DUAL_RANGE_RADAR = 0x283
KEY_RADAR_OVERLAY = 0x284
KEY_TRADITIONAL_SONAR = 0x285
KEY_CLEARVU_SONAR = 0x286
KEY_SIDEVU_SONAR = 0x287
KEY_NAV_INFO = 0x288
KEY_BRIGHTNESS_MENU = 0x289

# Macro Keys
KEY_MACRO1 = 0x290
KEY_MACRO2 = 0x291
KEY_MACRO3 = 0x292
KEY_MACRO4 = 0x293
KEY_MACRO5 = 0x294
KEY_MACRO6 = 0x295
KEY_MACRO7 = 0x296
KEY_MACRO8 = 0x297
KEY_MACRO9 = 0x298
KEY_MACRO10 = 0x299
KEY_MACRO11 = 0x29A
KEY_MACRO12 = 0x29B
KEY_MACRO13 = 0x29C
KEY_MACRO14 = 0x29D
KEY_MACRO15 = 0x29E
KEY_MACRO16 = 0x29F
KEY_MACRO17 = 0x2A0
KEY_MACRO18 = 0x2A1
KEY_MACRO19 = 0x2A2
KEY_MACRO20 = 0x2A3
KEY_MACRO21 = 0x2A4
KEY_MACRO22 = 0x2A5
KEY_MACRO23 = 0x2A6
KEY_MACRO24 = 0x2A7
KEY_MACRO25 = 0x2A8
KEY_MACRO26 = 0x2A9
KEY_MACRO27 = 0x2AA
KEY_MACRO28 = 0x2AB
KEY_MACRO29 = 0x2AC
KEY_MACRO30 = 0x2AD

# Macro Recording and Preset Keys
KEY_MACRO_RECORD_START = 0x2B0
KEY_MACRO_RECORD_STOP = 0x2B1
KEY_MACRO_PRESET_CYCLE = 0x2B2
KEY_MACRO_PRESET1 = 0x2B3
KEY_MACRO_PRESET2 = 0x2B4
KEY_MACRO_PRESET3 = 0x2B5

# Keyboard LCD Menu Keys
KEY_KBD_LCD_MENU1 = 0x2B8
KEY_KBD_LCD_MENU2 = 0x2B9
KEY_KBD_LCD_MENU3 = 0x2BA
KEY_KBD_LCD_MENU4 = 0x2BB
KEY_KBD_LCD_MENU5 = 0x2BC

# Trigger Happy Buttons
BTN_TRIGGER_HAPPY = 0x2C0
BTN_TRIGGER_HAPPY1 = 0x2C0
BTN_TRIGGER_HAPPY2 = 0x2C1
BTN_TRIGGER_HAPPY3 = 0x2C2
BTN_TRIGGER_HAPPY4 = 0x2C3
BTN_TRIGGER_HAPPY5 = 0x2C4
BTN_TRIGGER_HAPPY6 = 0x2C5
BTN_TRIGGER_HAPPY7 = 0x2C6
BTN_TRIGGER_HAPPY8 = 0x2C7
BTN_TRIGGER_HAPPY9 = 0x2C8
BTN_TRIGGER_HAPPY10 = 0x2C9
BTN_TRIGGER_HAPPY11 = 0x2CA
BTN_TRIGGER_HAPPY12 = 0x2CB
BTN_TRIGGER_HAPPY13 = 0x2CC
BTN_TRIGGER_HAPPY14 = 0x2CD
BTN_TRIGGER_HAPPY15 = 0x2CE
BTN_TRIGGER_HAPPY16 = 0x2CF
BTN_TRIGGER_HAPPY17 = 0x2D0
BTN_TRIGGER_HAPPY18 = 0x2D1
BTN_TRIGGER_HAPPY19 = 0x2D2
BTN_TRIGGER_HAPPY20 = 0x2D3
BTN_TRIGGER_HAPPY21 = 0x2D4
BTN_TRIGGER_HAPPY22 = 0x2D5
BTN_TRIGGER_HAPPY23 = 0x2D6
BTN_TRIGGER_HAPPY24 = 0x2D7
BTN_TRIGGER_HAPPY25 = 0x2D8
BTN_TRIGGER_HAPPY26 = 0x2D9
BTN_TRIGGER_HAPPY27 = 0x2DA
BTN_TRIGGER_HAPPY28 = 0x2DB
BTN_TRIGGER_HAPPY29 = 0x2DC
BTN_TRIGGER_HAPPY30 = 0x2DD
BTN_TRIGGER_HAPPY31 = 0x2DE
BTN_TRIGGER_HAPPY32 = 0x2DF
BTN_TRIGGER_HAPPY33 = 0x2E0
BTN_TRIGGER_HAPPY34 = 0x2E1
BTN_TRIGGER_HAPPY35 = 0x2E2
BTN_TRIGGER_HAPPY36 = 0x2E3
BTN_TRIGGER_HAPPY37 = 0x2E4
BTN_TRIGGER_HAPPY38 = 0x2E5
BTN_TRIGGER_HAPPY39 = 0x2E6
BTN_TRIGGER_HAPPY40 = 0x2E7

# Relative Axes
REL_X = 0x00
REL_Y = 0x01
REL_Z = 0x02
REL_RX = 0x03
REL_RY = 0x04
REL_RZ = 0x05
REL_HWHEEL = 0x06
REL_DIAL = 0x07
REL_WHEEL = 0x08
REL_MISC = 0x09
REL_RESERVED = 0x0A
REL_WHEEL_HI_RES = 0x0B
REL_HWHEEL_HI_RES = 0x0C
REL_MAX = 0x0F
REL_CNT = REL_MAX + 1

# Absolute Axes
ABS_X = 0x00
ABS_Y = 0x01
ABS_Z = 0x02
ABS_RX = 0x03
ABS_RY = 0x04
ABS_RZ = 0x05
ABS_THROTTLE = 0x06
ABS_RUDDER = 0x07
ABS_WHEEL = 0x08
ABS_GAS = 0x09
ABS_BRAKE = 0x0A
ABS_HAT0X = 0x10
ABS_HAT0Y = 0x11
ABS_HAT1X = 0x12
ABS_HAT1Y = 0x13
ABS_HAT2X = 0x14
ABS_HAT2Y = 0x15
ABS_HAT3X = 0x16
ABS_HAT3Y = 0x17
ABS_PRESSURE = 0x18
ABS_DISTANCE = 0x19
ABS_TILT_X = 0x1A
ABS_TILT_Y = 0x1B
ABS_TOOL_WIDTH = 0x1C
ABS_VOLUME = 0x20
ABS_PROFILE = 0x21
ABS_MISC = 0x28
ABS_RESERVED = 0x2E
ABS_MT_SLOT = 0x2F
ABS_MT_TOUCH_MAJOR = 0x30
ABS_MT_TOUCH_MINOR = 0x31
ABS_MT_WIDTH_MAJOR = 0x32
ABS_MT_WIDTH_MINOR = 0x33
ABS_MT_ORIENTATION = 0x34
ABS_MT_POSITION_X = 0x35
ABS_MT_POSITION_Y = 0x36
ABS_MT_TOOL_TYPE = 0x37
ABS_MT_BLOB_ID = 0x38
ABS_MT_TRACKING_ID = 0x39
ABS_MT_PRESSURE = 0x3A
ABS_MT_DISTANCE = 0x3B
ABS_MT_TOOL_X = 0x3C
ABS_MT_TOOL_Y = 0x3D
ABS_MAX = 0x3F
ABS_CNT = ABS_MAX + 1

# Switch Events
SW_LID = 0x00
SW_TABLET_MODE = 0x01
SW_HEADPHONE_INSERT = 0x02
SW_RFKILL_ALL = 0x03
SW_RADIO = SW_RFKILL_ALL
SW_MICROPHONE_INSERT = 0x04
SW_DOCK = 0x05
SW_LINEOUT_INSERT = 0x06
SW_JACK_PHYSICAL_INSERT = 0x07
SW_VIDEOOUT_INSERT = 0x08
SW_CAMERA_LENS_COVER = 0x09
SW_KEYPAD_SLIDE = 0x0A
SW_FRONT_PROXIMITY = 0x0B
SW_ROTATE_LOCK = 0x0C
SW_LINEIN_INSERT = 0x0D
SW_MUTE_DEVICE = 0x0E
SW_PEN_INSERTED = 0x0F
SW_MACHINE_COVER = 0x10
SW_MAX = 0x10
SW_CNT = SW_MAX + 1

# Misc Events
MSC_SERIAL = 0x00
MSC_PULSELED = 0x01
MSC_GESTURE = 0x02
MSC_RAW = 0x03
MSC_SCAN = 0x04
MSC_TIMESTAMP = 0x05
MSC_MAX = 0x07
MSC_CNT = MSC_MAX + 1

# LEDs
LED_NUML = 0x00
LED_CAPSL = 0x01
LED_SCROLLL = 0x02
LED_COMPOSE = 0x03
LED_KANA = 0x04
LED_SLEEP = 0x05
LED_SUSPEND = 0x06
LED_MUTE = 0x07
LED_MISC = 0x08
LED_MAIL = 0x09
LED_CHARGING = 0x0A
LED_MAX = 0x0F
LED_CNT = LED_MAX + 1

# Autorepeat values
REP_DELAY = 0x00
REP_PERIOD = 0x01
REP_MAX = 0x01
REP_CNT = REP_MAX + 1

# Sounds
SND_CLICK = 0x00
SND_BELL = 0x01
SND_TONE = 0x02
SND_MAX = 0x07
SND_CNT = SND_MAX + 1
